post http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IktpbmdLb2RlIiwiaWQiOiI1ZTA5MzMyMzQxYzBkMjVhZTRjNDJhYzciLCJpYXQiOjE1Nzc3NDEzOTB9.8zK7BBhbdu8bHi2XeO16U_6zgNaTiHvO1tI2BmumIk4
# Authorization: bearer INVALIDeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IktpbmdLb2RlIiwiaWQiOiI1ZTA5MzMyMzQxYzBkMjVhZTRjNDJhYzciLCJpYXQiOjE1Nzc3NDEzOTB9.8zK7BBhbdu8bHi2XeO16U_6zgNaTiHvO1tI2BmumIk4

# token is for KingKode user
{
    "title": "New Blog Title",
    "content": "New Blog Content",
    "author": "New Blog Author",
    "url": "New Blog Url",
    "likes": 5
}